tasks:
  - name: "Init"
    command: |
      #!/usr/bin/env sh
      set -e
      # Download V
      if [ ! -e 'v/' ]
      then
        git clone https://github.com/vlang/v
      fi
      # Make V
      cd v
      if [ ! -e './v' ]
      then
        make
      fi
      # Symlink V
      sudo ./v symlink
      cd ..
      # Download v-analyzer
      v download -RD https://raw.githubusercontent.com/vlang/v-analyzer/main/install.vsh
      # Download Clockwork
      v download -RD https://raw.githubusercontent.com/EmmaTheMartian/clockwork/refs/heads/main/scripts/install.vsh
      # Install project dependencies
      clockwork deps
