name: build musi

on:
  push:
    paths:
      - '.github/workflows/build.yml'
  workflow_run:
    workflows: [test musi]
    types: [completed]

permissions:
  contents: read

concurrency:
  group: "build"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup V
        uses: vlang/setup-v@v1.4
        with:
          stable: true
      - name: Download Clockwork
        run: v download -RD https://raw.githubusercontent.com/EmmaTheMartian/clockwork/refs/heads/main/scripts/install.vsh
      - name: Build
        run: clockwork build.prod
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'musi-linux'
          path: 'build/main'
