name: deploy documentation

on:
  push:
    paths:
      - '.github/workflows/docs.yml'
  workflow_run:
    workflows: [test musi]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'musi/'
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Setup V
        uses: vlang/setup-v@v1.4
        with:
          stable: true
      - name: Generate docs
        run: v doc -f html -o apidocs/ -readme -m .
        working-directory: musi/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'musi/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
